### ISSUE TITLE
Errors in console (Bukkit 1.6.4 R2)

### ISSUE THREAD

**Issue by geshsi** [aarontwf/BattleNight-Core#122] opened 2013-11-18 12:53 UTC
I am having the following error when executing the following commands.

![error](https://f.cloud.github.com/assets/3117866/1562765/501f0a4c-5050-11e3-8f40-c0b65934f7cd.JPG)

**Comment by aarontwf** [comment] 2014-07-12 11:42
Duplicate of #123

**Closed as completed by aarontwf** 2014-07-12 11:42 UTC
Labels: Bug, Duplicate
