### ISSUE TITLE
Players losing their previous inventory

### ISSUE THREAD

**Issue by domjackson15** [aarontwf/BattleNight-Core#79] opened 2012-12-06 06:50 UTC
Some of the players have had their previous inventory cleared when they picked a class, then when the battle ended, their inventory was not there.

**Comment by aarontwf** [comment] 2012-12-06 21:04
This has nothing to do with Minecraft versions as they do not affect plugins, its the Bukkit versions which do on the very rare occasion.  The issue you are having is either caused by a bug in BattleNight, a conflict with another plugin or both.

Would you be able to do some troubleshooting on when they lose there inventory and under what circumstances.  Also can you pleas provide your CraftBukkit version, BattleNight version and the other plugins you are running.

Thanks

**Comment by wrecktify** [comment] 2012-12-08 04:33
Having the same issue.  Can not find any consistency on when a player loses their inventory or why.  

Latest version of battle night.

This server is running CraftBukkit version git-Bukkit-1.4.5-R0.2-11-g54ef53e-b2502jnks (MC: 1.4.5) (Implementing API version 1.4.5-R0.3-SNAPSHOT)

Plugins (38): WorldEdit, TagAPI, ColoredSigns, BattleNight, LogBlockQuestioner, Vault, PermissionsEx, PlayerHeads, Multiverse-Core, MobBountyReloaded, LogBlock, Questioner, WorldGuard, ColourFireWorks, BouncyBeds, Spectate, Shopkeepers, Minigames, Announcer, pvparena, MineMaze, OpenInv, Lockette, FirstJoinPlus, Votifier, WeatherMan, FoundDiamonds, Lift, Essentials, Towny, EssentialsSpawn, AntiShare, PaidSwitch, EssentialsAntiBuild, ChestShop, MobArena, ShowCaseStandalone, TownyChat

**Comment by wrecktify** [comment] 2012-12-08 04:59
One thing I noticed is it still has the [BN] tag on the names of players who lose items when the arena ends.  The tag never goes away.

**Comment by wrecktify** [comment] 2012-12-08 05:07
Pretty much every player is getting stuck with [BN] on their name when pressing TAB.  I set down some TNT with the pyro class in game and they didnt disappear when the round ended.

**Comment by jemajema** [comment] 2012-12-13 22:49
All players lose their inventory, if the battle was over suicide of one of the players.
After the match, they still have inventory for the selected class.

**Comment by aarontwf** [comment] 2012-12-24 06:22
Fixed in 1.4.9.

**Closed as completed by aarontwf** 2012-12-24 06:22 UTC
Labels: Bug
