### ISSUE TITLE
Problems with waypoints and player's XP.

### ISSUE THREAD

**Issue by LynnJordison** [aarontwf/BattleNight-Core#53] opened 2012-09-20 17:50 UTC
Hi! I've been having a couple of problems since I updated the plugin.

First, when players type /bn join, most of the times they are teleported below the waypoint, and get stucked in walls or start drowning. I've tried with different versions of the plugin as well as Bukkit versions and it still happens, although it's random and doesn't happen EVERY single time. 

Second, when a battle ends, the players lose all their experience levels, this always happens and I don't know how to fix that. Also, sometimes they keep their Battlenight class inventory, and their survival inventory dissappears after leaving.

I'm now testing this with the dev versions you've posted over this forum, I'll let you know if anything gets fixed, and will appreciate any help provided.

Thanks a lot!

**Comment by Arcental** [comment] 2012-09-21 00:34
Try putting the way point 1 block up from the floor

**Comment by LynnJordison** [comment] 2012-09-21 01:10
Already tried that, but it keeps stucking players on the floor below the waypoint :(

**Comment by aarontwf** [comment] 2012-09-21 11:30
Hmm, its sort of a Bukkit teleport bug and seems to happen to me only if the arena is on a different world.  I think is is caused by the chunk not loading in time.  Ill try load the chunk first so that is ready for TPs and see if it fixes it.

**Comment by LynnJordison** [comment] 2012-09-21 16:15
In this case I have the arena on the main world, could it be that it still doesn't load in time when the players teleport to it?
I'll try changing Bukkit builds to see if it stops happening.

Thanks for the help!

**Comment by aarontwf** [comment] 2012-09-25 07:49
Ok, I have just finished [the new dev version](http://bit.ly/bnlatestdev) which should have fixed a whole lot of bugs.

If do however find any bugs in this version please post them here.

**Comment by aarontwf** [comment] 2012-09-30 00:37
XP has been fixed in dev version.  Will be released sometime this week.

**Closed as completed** 2012-11-05 08:17 UTC
Labels: Bug
